name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  deploy:
    name: deploy-gcf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Build Nodeaccio
        run: |
          gcloud builds submit --tag gcr.io/provisionier/nodeaccio

      - name: Deploy Nodeaccio
        run: |
          gcloud run deploy probot --image gcr.io/provisionier/nodeaccio --platform managed --region us-west1